version: '3.2'
services:
  kuso-subdomain-adder:
    #build: .
    image: ghcr.io/sksat/kuso-subdomain-adder:${VERSION}
    restart: always
    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
      - ./template:/app/template
    ports:
      - 8101:8101
  tunnel:
    image: cloudflare/cloudflared:2021.7.4
    restart: always
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel --hostname ${HOSTNAME} --url http://kuso-subdomain-adder:8101
