name: CI

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain'
      - '.github/workflows/ci.yml'
  push:
    branches:
      - master
      - dev-*

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: install cargo-make
        uses: davidB/rust-cargo-make@v1.6.0

      - name: check cargo-make version
        run: |
          cargo-make --version
          cargo-make make --version
          makers --version

      - name: cache dependencies
        uses: Swatinem/rust-cache@v1.3.0

      - name: clippy check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: compile for unit test
        run: cargo test --no-run --locked

      - name: unit test
        run: cargo test
