name: Daily Container Image Vulnerability Scan

on:
  push:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'master'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull ghcr.io/sksat/kuso-subdomain-adder:${{ github.event.inputs.tag || "master" }}

      - uses: lazy-actions/gitrivy@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/sksat/kuso-subdomain-adder:master
