name: Daily Container Image Vulnerability Scan

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'master'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull ghcr.io/sksat/kuso-subdomain-adder:${{ github.event.inputs.tag }}

      - uses: lazy-actions/gitrivy@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/sksat/kuso-subdomain-adder:master
