name: Daily Container Image Vulnerability Scan

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'master'

jobs:
  scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.2.2
        with:
          image-ref: "ghcr.io/sksat/kuso-subdomain-adder:${{ github.event.inputs.tag || 'master' }}"
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1.1.0
        with:
          sarif_file: 'trivy-results.sarif'

  scan-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.2.2
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1.1.0
        with:
          sarif_file: 'trivy-results.sarif'
